name: train_rf
version: 1
inputs:
  train_data:
    type: uri_file
  model_out:
    type: uri_folder
  register_model:
    type: string
    optional: true
outputs:
  model:
    type: uri_folder
code: .
command: >-
  python train_rf.py --train_data ${{inputs.train_data}} --model_out ${{outputs.model}} --register_model ${{inputs.register_model}}
environment: ../../envs/conda.yml
description: Entrena un modelo Random Forest para clasificación de clima.
