name: weather-mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - azure-ai-ml
      - azure-identity
      - pandas
      - numpy
      - scikit-learn==1.6.1    # Fijamos versión compatible
      - matplotlib
      - seaborn
      - azureml-mlflow
      - azureml-core
      - azureml-defaults
      - azure-ai-textanalytics==5.3.0 # Nueva dependencia para Azure Text Analytics
      - azure-core==1.29.0 # Nueva dependencia para Azure Core
